//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_WS_Cliente_Basico_Hinojosa.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WS_ServerSoap")]
    public interface WS_ServerSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldResponse HelloWorld(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldResponse> HelloWorldAsync(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SaludosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saludos", ReplyAction="*")]
        lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosResponse Saludos(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saludos", ReplyAction="*")]
        System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosResponse> SaludosAsync(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        double Suma(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SumaAsync(double num1, double num2);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operaciones", ReplyAction="*")]
        lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesResponse Operaciones(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesResponse> OperacionesAsync(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Tabla1Result del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tabla1", ReplyAction="*")]
        lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Response Tabla1(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tabla1", ReplyAction="*")]
        System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Response> Tabla1Async(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Tabla2Result del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tabla2", ReplyAction="*")]
        lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Response Tabla2(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tabla2", ReplyAction="*")]
        System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Response> Tabla2Async(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAñosTipos", ReplyAction="*")]
        lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposResponse ListarAñosTipos(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAñosTipos", ReplyAction="*")]
        System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposResponse> ListarAñosTiposAsync(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Saludos", Namespace="http://tempuri.org/", Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosRequestBody Body;
        
        public SaludosRequest() {
        }
        
        public SaludosRequest(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaludosRequestBody {
        
        public SaludosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaludosResponse", Namespace="http://tempuri.org/", Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosResponseBody Body;
        
        public SaludosResponse() {
        }
        
        public SaludosResponse(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaludosResult;
        
        public SaludosResponseBody() {
        }
        
        public SaludosResponseBody(string SaludosResult) {
            this.SaludosResult = SaludosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OperacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Operaciones", Namespace="http://tempuri.org/", Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesRequestBody Body;
        
        public OperacionesRequest() {
        }
        
        public OperacionesRequest(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OperacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double num2;
        
        public OperacionesRequestBody() {
        }
        
        public OperacionesRequestBody(string tipo, double num1, double num2) {
            this.tipo = tipo;
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OperacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OperacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesResponseBody Body;
        
        public OperacionesResponse() {
        }
        
        public OperacionesResponse(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OperacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double OperacionesResult;
        
        public OperacionesResponseBody() {
        }
        
        public OperacionesResponseBody(double OperacionesResult) {
            this.OperacionesResult = OperacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Tabla1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tabla1", Namespace="http://tempuri.org/", Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1RequestBody Body;
        
        public Tabla1Request() {
        }
        
        public Tabla1Request(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Tabla1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numero;
        
        public Tabla1RequestBody() {
        }
        
        public Tabla1RequestBody(int numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Tabla1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tabla1Response", Namespace="http://tempuri.org/", Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1ResponseBody Body;
        
        public Tabla1Response() {
        }
        
        public Tabla1Response(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Tabla1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tabla1Result;
        
        public Tabla1ResponseBody() {
        }
        
        public Tabla1ResponseBody(string Tabla1Result) {
            this.Tabla1Result = Tabla1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Tabla2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tabla2", Namespace="http://tempuri.org/", Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2RequestBody Body;
        
        public Tabla2Request() {
        }
        
        public Tabla2Request(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Tabla2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numero;
        
        public Tabla2RequestBody() {
        }
        
        public Tabla2RequestBody(int numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Tabla2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tabla2Response", Namespace="http://tempuri.org/", Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2ResponseBody Body;
        
        public Tabla2Response() {
        }
        
        public Tabla2Response(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Tabla2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ArrayOfString Tabla2Result;
        
        public Tabla2ResponseBody() {
        }
        
        public Tabla2ResponseBody(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ArrayOfString Tabla2Result) {
            this.Tabla2Result = Tabla2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarAñosTiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarAñosTipos", Namespace="http://tempuri.org/", Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposRequestBody Body;
        
        public ListarAñosTiposRequest() {
        }
        
        public ListarAñosTiposRequest(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarAñosTiposRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int anioInicial;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int anioFinal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipo;
        
        public ListarAñosTiposRequestBody() {
        }
        
        public ListarAñosTiposRequestBody(int anioInicial, int anioFinal, string tipo) {
            this.anioInicial = anioInicial;
            this.anioFinal = anioFinal;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarAñosTiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarAñosTiposResponse", Namespace="http://tempuri.org/", Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposResponseBody Body;
        
        public ListarAñosTiposResponse() {
        }
        
        public ListarAñosTiposResponse(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarAñosTiposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ArrayOfString ListarAñosTiposResult;
        
        public ListarAñosTiposResponseBody() {
        }
        
        public ListarAñosTiposResponseBody(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ArrayOfString ListarAñosTiposResult) {
            this.ListarAñosTiposResult = ListarAñosTiposResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_ServerSoapChannel : lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_ServerSoapClient : System.ServiceModel.ClientBase<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap>, lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap {
        
        public WS_ServerSoapClient() {
        }
        
        public WS_ServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_ServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_ServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_ServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldResponse lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap.HelloWorld(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldRequest inValue = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldRequest();
            inValue.Body = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldRequestBody();
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldResponse retVal = ((lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldResponse> lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap.HelloWorldAsync(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldRequest inValue = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldRequest();
            inValue.Body = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.HelloWorldRequestBody();
            return ((lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosResponse lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap.Saludos(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosRequest request) {
            return base.Channel.Saludos(request);
        }
        
        public string Saludos() {
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosRequest inValue = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosRequest();
            inValue.Body = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosRequestBody();
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosResponse retVal = ((lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap)(this)).Saludos(inValue);
            return retVal.Body.SaludosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosResponse> lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap.SaludosAsync(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosRequest request) {
            return base.Channel.SaludosAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosResponse> SaludosAsync() {
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosRequest inValue = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosRequest();
            inValue.Body = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.SaludosRequestBody();
            return ((lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap)(this)).SaludosAsync(inValue);
        }
        
        public double Suma(double num1, double num2) {
            return base.Channel.Suma(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> SumaAsync(double num1, double num2) {
            return base.Channel.SumaAsync(num1, num2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesResponse lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap.Operaciones(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesRequest request) {
            return base.Channel.Operaciones(request);
        }
        
        public double Operaciones(string tipo, double num1, double num2) {
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesRequest inValue = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesRequest();
            inValue.Body = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesRequestBody();
            inValue.Body.tipo = tipo;
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesResponse retVal = ((lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap)(this)).Operaciones(inValue);
            return retVal.Body.OperacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesResponse> lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap.OperacionesAsync(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesRequest request) {
            return base.Channel.OperacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesResponse> OperacionesAsync(string tipo, double num1, double num2) {
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesRequest inValue = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesRequest();
            inValue.Body = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.OperacionesRequestBody();
            inValue.Body.tipo = tipo;
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap)(this)).OperacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Response lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap.Tabla1(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Request request) {
            return base.Channel.Tabla1(request);
        }
        
        public string Tabla1(int numero) {
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Request inValue = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Request();
            inValue.Body = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1RequestBody();
            inValue.Body.numero = numero;
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Response retVal = ((lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap)(this)).Tabla1(inValue);
            return retVal.Body.Tabla1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Response> lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap.Tabla1Async(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Request request) {
            return base.Channel.Tabla1Async(request);
        }
        
        public System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Response> Tabla1Async(int numero) {
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Request inValue = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1Request();
            inValue.Body = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla1RequestBody();
            inValue.Body.numero = numero;
            return ((lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap)(this)).Tabla1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Response lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap.Tabla2(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Request request) {
            return base.Channel.Tabla2(request);
        }
        
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ArrayOfString Tabla2(int numero) {
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Request inValue = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Request();
            inValue.Body = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2RequestBody();
            inValue.Body.numero = numero;
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Response retVal = ((lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap)(this)).Tabla2(inValue);
            return retVal.Body.Tabla2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Response> lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap.Tabla2Async(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Request request) {
            return base.Channel.Tabla2Async(request);
        }
        
        public System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Response> Tabla2Async(int numero) {
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Request inValue = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2Request();
            inValue.Body = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.Tabla2RequestBody();
            inValue.Body.numero = numero;
            return ((lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap)(this)).Tabla2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposResponse lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap.ListarAñosTipos(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposRequest request) {
            return base.Channel.ListarAñosTipos(request);
        }
        
        public lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ArrayOfString ListarAñosTipos(int anioInicial, int anioFinal, string tipo) {
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposRequest inValue = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposRequest();
            inValue.Body = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposRequestBody();
            inValue.Body.anioInicial = anioInicial;
            inValue.Body.anioFinal = anioFinal;
            inValue.Body.tipo = tipo;
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposResponse retVal = ((lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap)(this)).ListarAñosTipos(inValue);
            return retVal.Body.ListarAñosTiposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposResponse> lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap.ListarAñosTiposAsync(lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposRequest request) {
            return base.Channel.ListarAñosTiposAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposResponse> ListarAñosTiposAsync(int anioInicial, int anioFinal, string tipo) {
            lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposRequest inValue = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposRequest();
            inValue.Body = new lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.ListarAñosTiposRequestBody();
            inValue.Body.anioInicial = anioInicial;
            inValue.Body.anioFinal = anioFinal;
            inValue.Body.tipo = tipo;
            return ((lab_WS_Cliente_Basico_Hinojosa.ServiceReference1.WS_ServerSoap)(this)).ListarAñosTiposAsync(inValue);
        }
    }
}
